---
# tasks file for java

    - name: "Get the hosts username"
      become: false
      local_action: 'command whoami'
      register: 'user'
    - name: "install required soft (net-tools, java)"
      apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 40000
        name: '{{ item }}'
        state: present
      become: true  
      loop: '{{  programs }}'
    - name: 'copy ServiceOne files'
      copy:
        src: "/home/{{ user.stdout }}/epam_final_project/project_samples/service-one/{{item}}"
        dest: "{{ userdir }}service-one" 
      loop: '{{ app1 }}' 
    - name: 'copy template'
      copy: 
        src: "/home/{{ user.stdout }}/epam_final_project/temp/{{item}}"
        dest: "{{ userdir }}"
        mode: '0660'
      loop: '{{ copyfile }}'
    - name: "copy user_data_script"
      copy: 
        src: "/home/{{ user.stdout }}/epam_final_project/project_build/scripts/{{ scripts[2] }}"
        dest: "{{ userdir }} "
        mode: '0770'
    - name: 'copy service'
      copy: 
        src: "/home/{{ user.stdout }}/epam_final_project/project_build/servicesfiles/{{ services[2] }}"
        dest: "{{ systemservicepath }}"
      become: true
...