---
    - name: "wget erlang"
      get_url: 
        url: "https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb"
        dest: "{{ userdir }}"
        mode: '774'
    - name: "install deb"
      apt:
        deb: "erlang-solutions_1.0_all.deb"
        update_cache: true
        force_apt_get: true
        cache_valid_time: 40000
        state: present
      become: true
    - name: "install erlang"
      apt:
        name: "erlang"
        update_cache: true
        force_apt_get: true
        cache_valid_time: 4000
        state: present
      become: true
    - name: "install erlang-nox"
      apt: 
        name: "erlang-nox"
        update_cache: true
        force_apt_get: true
        cache_valid_time: 4000
        state: present
      become: true    
    - name: "shell command"
      shell: 
        echo 'deb http://www.rabbitmq.com/debian/ testing main' | sudo tee /etc/apt/sources.list.d/rabbitmq.list
    - name: "Add key"
      apt_key:
        url: "{{ mqkeypath }}"
        state: present
      become: true
    - name: 'install required soft (rabbitmq, net-tools)'
      apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 40000
        name: '{{ item }}'
        state: present
      become: true  
      loop: '{{  program_list }}'
    - name: "Enable rabbitmq management plugin"
      shell:
        rabbitmq-plugins enable rabbitmq_management
      become: true
    - community.rabbitmq.rabbitmq_user:
        user: admin
        password: password
        permissions:
          - vhost: /
            configure_priv: .*
            read_priv: .*
            write_priv: .*
        state: present
      become: true
    - name: "Config admin user as administrator"
      shell:
        rabbitmqctl set_user_tags admin administrator
      become: true
    - name: "Check status rabbitmq's service"
      systemd: 
        name: "rabbitmq-server"
        state: started
        enabled: true
      become: true
...
